/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjetoController;
import javax.swing.JOptionPane;
import model.Projetos;

/**
 *
 * @author jbali
 */
public class AdcProjetoScreen extends javax.swing.JDialog {

    /**
     * Creates new form AdcProjetoScreen
     */
    ProjetoController controlador;//Declara o controlador do projeto
    int idUsuario;

    public AdcProjetoScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        controlador = new ProjetoController();//Instancia o objeto controlador do projeto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_titulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        btn_adcProjeto = new javax.swing.JLabel();
        pnl_form = new javax.swing.JPanel();
        lbl_nomeProjeto = new javax.swing.JLabel();
        txt_nomeProjeto = new javax.swing.JTextField();
        lbl_descricaoProjeto = new javax.swing.JLabel();
        spn_descricaoProjeto = new javax.swing.JScrollPane();
        txt_descricaoProjeto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar projeto");
        setMinimumSize(new java.awt.Dimension(300, 450));
        setPreferredSize(new java.awt.Dimension(400, 450));

        pnl_titulo.setBackground(new java.awt.Color(0, 153, 102));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Novo Projeto");

        btn_adcProjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_adcProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        btn_adcProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adcProjetoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_adcProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_adcProjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        pnl_form.setBackground(new java.awt.Color(255, 255, 255));

        lbl_nomeProjeto.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nomeProjeto.setText("* Nome");

        txt_nomeProjeto.setBackground(new java.awt.Color(255, 255, 255));
        txt_nomeProjeto.setForeground(new java.awt.Color(0, 0, 0));
        txt_nomeProjeto.setToolTipText("Preencha com o nome do projeto");

        lbl_descricaoProjeto.setForeground(new java.awt.Color(0, 0, 0));
        lbl_descricaoProjeto.setText("Descrição");

        txt_descricaoProjeto.setBackground(new java.awt.Color(255, 255, 255));
        txt_descricaoProjeto.setColumns(20);
        txt_descricaoProjeto.setForeground(new java.awt.Color(0, 0, 0));
        txt_descricaoProjeto.setRows(5);
        txt_descricaoProjeto.setToolTipText("Preencha com a descrição do projeto");
        spn_descricaoProjeto.setViewportView(txt_descricaoProjeto);

        javax.swing.GroupLayout pnl_formLayout = new javax.swing.GroupLayout(pnl_form);
        pnl_form.setLayout(pnl_formLayout);
        pnl_formLayout.setHorizontalGroup(
            pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spn_descricaoProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(lbl_nomeProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nomeProjeto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_descricaoProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_formLayout.setVerticalGroup(
            pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_formLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_nomeProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_descricaoProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn_descricaoProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adcProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adcProjetoMouseClicked
        //Validação de dados: impede que o projeto seja salvo sem nome
        if ("".equals(txt_nomeProjeto.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Insira um nome para o projeto", "Aviso", 0);
        } else {
            
            try {
                //Cria objeto Projeto e atribui valores aos atributos
                Projetos projeto = new Projetos();
                projeto.setNome(txt_nomeProjeto.getText());
                projeto.setDescricao(txt_descricaoProjeto.getText());

                controlador.incluir(projeto, idUsuario);//Envia os dados ao controlador e salva no BD

                //Mostra uma caixa de diálogo confirmando a criação do projeto
                JOptionPane.showMessageDialog(rootPane, "Projeto salvo com sucesso!", "Sucesso", 1);
                
                this.dispose();//Fecha janela
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar o projeto\n" + e, "Erro", 0);
            }
        }
    }//GEN-LAST:event_btn_adcProjetoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java Swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdcProjetoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdcProjetoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdcProjetoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdcProjetoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdcProjetoScreen dialog = new AdcProjetoScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_adcProjeto;
    private javax.swing.JLabel lbl_descricaoProjeto;
    private javax.swing.JLabel lbl_nomeProjeto;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_form;
    private javax.swing.JPanel pnl_titulo;
    private javax.swing.JScrollPane spn_descricaoProjeto;
    private javax.swing.JTextArea txt_descricaoProjeto;
    private javax.swing.JTextField txt_nomeProjeto;
    // End of variables declaration//GEN-END:variables

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
}
