/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TarefaController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Tarefas;
import model.Projetos;

/**
 *
 * @author jbali
 */
public class AdcTarefaScreen extends javax.swing.JDialog {

    /**
     * Creates new form AdcTarefaScreen
     */
    
    TarefaController controlador;//Declara o controlador da tarefa
    Projetos projeto;//Declara um projeto
    
    public AdcTarefaScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controlador = new TarefaController();//Instancia o controlador
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_titulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        btn_adcTarefa = new javax.swing.JLabel();
        pnl_form = new javax.swing.JPanel();
        lbl_nomeTarefa = new javax.swing.JLabel();
        txt_nomeTarefa = new javax.swing.JTextField();
        lbl_descricaoTarefa = new javax.swing.JLabel();
        spn_descricaoTarefa = new javax.swing.JScrollPane();
        txt_descricaoTarefa = new javax.swing.JTextArea();
        lbl_prazoTarefa = new javax.swing.JLabel();
        txt_prazoTarefa = new javax.swing.JFormattedTextField();
        lbl_obsTarefa = new javax.swing.JLabel();
        spn_obsTarefa = new javax.swing.JScrollPane();
        txt_obsTarefa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Tarefa");
        setMinimumSize(new java.awt.Dimension(400, 536));
        setResizable(false);

        pnl_titulo.setBackground(new java.awt.Color(0, 153, 102));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Nova Tarefa");

        btn_adcTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_adcTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        btn_adcTarefa.setToolTipText("Salvar tarefa");
        btn_adcTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adcTarefaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_adcTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_adcTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_form.setBackground(new java.awt.Color(255, 255, 255));

        lbl_nomeTarefa.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nomeTarefa.setText("Nome");

        txt_nomeTarefa.setBackground(new java.awt.Color(255, 255, 255));
        txt_nomeTarefa.setForeground(new java.awt.Color(0, 0, 0));
        txt_nomeTarefa.setToolTipText("Preencha com o nome da tarefa");

        lbl_descricaoTarefa.setForeground(new java.awt.Color(0, 0, 0));
        lbl_descricaoTarefa.setText("Descrição");

        txt_descricaoTarefa.setBackground(new java.awt.Color(255, 255, 255));
        txt_descricaoTarefa.setColumns(20);
        txt_descricaoTarefa.setForeground(new java.awt.Color(0, 0, 0));
        txt_descricaoTarefa.setRows(5);
        txt_descricaoTarefa.setToolTipText("Preencha com a descrição da tarefa");
        spn_descricaoTarefa.setViewportView(txt_descricaoTarefa);

        lbl_prazoTarefa.setForeground(new java.awt.Color(0, 0, 0));
        lbl_prazoTarefa.setText("Prazo");

        txt_prazoTarefa.setBackground(new java.awt.Color(255, 255, 255));
        txt_prazoTarefa.setForeground(new java.awt.Color(0, 0, 0));
        txt_prazoTarefa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        lbl_obsTarefa.setForeground(new java.awt.Color(0, 0, 0));
        lbl_obsTarefa.setText("Observações");

        txt_obsTarefa.setBackground(new java.awt.Color(255, 255, 255));
        txt_obsTarefa.setColumns(20);
        txt_obsTarefa.setForeground(new java.awt.Color(0, 0, 0));
        txt_obsTarefa.setRows(5);
        txt_obsTarefa.setToolTipText("Preencha com observações sobre a tarefa");
        spn_obsTarefa.setViewportView(txt_obsTarefa);

        javax.swing.GroupLayout pnl_formLayout = new javax.swing.GroupLayout(pnl_form);
        pnl_form.setLayout(pnl_formLayout);
        pnl_formLayout.setHorizontalGroup(
            pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nomeTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nomeTarefa)
                    .addComponent(lbl_descricaoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spn_descricaoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(lbl_prazoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_obsTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spn_obsTarefa)
                    .addComponent(txt_prazoTarefa))
                .addContainerGap())
        );
        pnl_formLayout.setVerticalGroup(
            pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_formLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_nomeTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nomeTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_descricaoTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn_descricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_prazoTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_prazoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_obsTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn_obsTarefa)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adcTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adcTarefaMouseClicked
        // TODO add your handling code here:
        //Validação de dados
        if("".equals(txt_nomeTarefa.getText())){
            JOptionPane.showMessageDialog(rootPane, "Insira o nome do projeto", "", 0);
        }else{
            try{
                SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");//Cria um novo formatação de data
                Date prazo = data.parse(txt_prazoTarefa.getText());//Converte o texto para o formato de data
                
                //Cria um objeto Tarefa e insere os valores
                Tarefas tarefa = new Tarefas();
                tarefa.setNome(txt_nomeTarefa.getText());
                tarefa.setDescricao(txt_descricaoTarefa.getText());
                tarefa.setObservacoes(txt_obsTarefa.getText());
                tarefa.setPrazo(prazo);
                tarefa.setConcluido(false);
//                tarefa.setProj_id(projeto.getId());
            tarefa.setProj_id(3);
                //Envia a tarefa para o controlador
                controlador.incluir(tarefa);
                
                //Confirmação
                JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso!", "Sucesso", 1);
                this.dispose();//Fecha a janela
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Erro ao inserir nova tarefa", "Erro", 0);
            }
        }
    }//GEN-LAST:event_btn_adcTarefaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdcTarefaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdcTarefaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdcTarefaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdcTarefaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdcTarefaScreen dialog = new AdcTarefaScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_adcTarefa;
    private javax.swing.JLabel lbl_descricaoTarefa;
    private javax.swing.JLabel lbl_nomeTarefa;
    private javax.swing.JLabel lbl_obsTarefa;
    private javax.swing.JLabel lbl_prazoTarefa;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_form;
    private javax.swing.JPanel pnl_titulo;
    private javax.swing.JScrollPane spn_descricaoTarefa;
    private javax.swing.JScrollPane spn_obsTarefa;
    private javax.swing.JTextArea txt_descricaoTarefa;
    private javax.swing.JTextField txt_nomeTarefa;
    private javax.swing.JTextArea txt_obsTarefa;
    private javax.swing.JFormattedTextField txt_prazoTarefa;
    // End of variables declaration//GEN-END:variables

    public void setProjeto(Projetos projeto) {
        this.projeto = projeto;
    }

    
}
