/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.UsuarioController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Usuarios;

/**
 *
 * @author jbali
 */
public class AdcUsuarioScreen extends javax.swing.JDialog {
    //ATRIBUTOS
    UsuarioController controlador;
    boolean editarUsuario;
    Usuarios usuario = new Usuarios();
    
    public AdcUsuarioScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        controlador = new UsuarioController();
        this.editarUsuario = false;
    }
    
    public AdcUsuarioScreen(java.awt.Frame parent, boolean modal, Usuarios usuario) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        controlador = new UsuarioController();
        this.usuario = usuario;
        preencherCampos();
        this.editarUsuario = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_titulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        btn_adcUsuario = new javax.swing.JLabel();
        pnl_adcUsuario = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        lbl_confirmSenha = new javax.swing.JLabel();
        txt_confirmSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setMinimumSize(new java.awt.Dimension(400, 352));
        setResizable(false);

        pnl_titulo.setBackground(new java.awt.Color(0, 153, 102));
        pnl_titulo.setPreferredSize(new java.awt.Dimension(400, 66));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Cadastro de Usuário");

        btn_adcUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_adcUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        btn_adcUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adcUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(btn_adcUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_adcUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_adcUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnl_adcUsuario.setForeground(new java.awt.Color(0, 0, 0));

        lbl_usuario.setText("Usuário");

        lbl_senha.setText("Senha");

        lbl_confirmSenha.setText("Confirmar Senha");

        javax.swing.GroupLayout pnl_adcUsuarioLayout = new javax.swing.GroupLayout(pnl_adcUsuario);
        pnl_adcUsuario.setLayout(pnl_adcUsuarioLayout);
        pnl_adcUsuarioLayout.setHorizontalGroup(
            pnl_adcUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adcUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_adcUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_usuario)
                    .addComponent(txt_senha)
                    .addGroup(pnl_adcUsuarioLayout.createSequentialGroup()
                        .addGroup(pnl_adcUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_usuario)
                            .addComponent(lbl_senha)
                            .addComponent(lbl_confirmSenha))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_confirmSenha))
                .addContainerGap())
        );
        pnl_adcUsuarioLayout.setVerticalGroup(
            pnl_adcUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adcUsuarioLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_confirmSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_confirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_adcUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_adcUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adcUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adcUsuarioMouseClicked
        String usuarioNome = txt_usuario.getText();
        String senha = new String(txt_senha.getPassword()).trim();
        String confirmSenha = new String(txt_confirmSenha.getPassword()).trim();
        
        if(senha.equals(confirmSenha) && !usuarioNome.equals("")) {
            usuario.setUsuario(usuarioNome);
            usuario.setSenha(senha);
            try{
                if(editarUsuario){
                    controlador.atualizar(usuario);
                    JOptionPane.showMessageDialog(rootPane, "Usuário atualizado com sucesso", "Atualização", -1);
                }else{
                    List<Usuarios> listaUsuarios = new ArrayList();
                    listaUsuarios = controlador.consultar();
                    boolean autorizaCadastro = true;

                    for(int i=0;i<listaUsuarios.size();i++){
                        if(usuarioNome.equals(listaUsuarios.get(i).getUsuario())){
                            JOptionPane.showMessageDialog(rootPane, "Usuário já existe", "Erro", 0);
                            autorizaCadastro = false;
                            break;
                        }
                    }

                    if(autorizaCadastro == true){
                        controlador.incluir(usuario);
                        JOptionPane.showMessageDialog(rootPane, "Usuário criado com sucesso!", "Usuário criado", 1);
                        this.dispose();
                    }
                }
                this.dispose();
            }catch(Exception e){
                if(editarUsuario) {
                    JOptionPane.showMessageDialog(rootPane, "Não foi possível atualizar o usuário", "Erro", 0);
                    throw new RuntimeException("Não foi possível atualizar o usuário\n"
                        + e.getMessage(),e);
                }
                else {
                    JOptionPane.showMessageDialog(rootPane, "Não foi possível criar um novo usuário\n"
                            + "Usuário inválido, já cadastrado ou senha inválida", "Erro", 0);
                    throw new RuntimeException("Não foi possível criar um novo usuário\n"
                        + "Usuário inválido, já cadastrado ou senha inválida" 
                        + e.getMessage(),e);
                }
                
            }
            
        }
        else JOptionPane.showMessageDialog(rootPane, "Usuário inválido ou senhas não batem", "Erro", 0);
        
    }//GEN-LAST:event_btn_adcUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java Swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdcUsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdcUsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdcUsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdcUsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdcUsuarioScreen dialog = new AdcUsuarioScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_adcUsuario;
    private javax.swing.JLabel lbl_confirmSenha;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel pnl_adcUsuario;
    private javax.swing.JPanel pnl_titulo;
    private javax.swing.JPasswordField txt_confirmSenha;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

    private void preencherCampos() {
        txt_usuario.setText(usuario.getUsuario());
        txt_usuario.setEnabled(false);
    }
}
