/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Usuarios;

/**
 *
 * @author jbali
 */
public class LoginScreen extends javax.swing.JFrame {

    UsuarioController controlador;
    
    public LoginScreen() {
        initComponents();
        setLocationRelativeTo(null);
        controlador = new UsuarioController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_titulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_login = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_recuperarSenha = new javax.swing.JLabel();
        btn_adcUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Todo App - Login");
        setResizable(false);

        pnl_titulo.setBackground(new java.awt.Color(0, 153, 102));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("TodoApp - Login");

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_login.setBackground(new java.awt.Color(255, 255, 255));

        lbl_usuario.setText("Usuário");

        lbl_senha.setText("Senha");

        btn_login.setText("Entrar");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });

        btn_recuperarSenha.setForeground(new java.awt.Color(0, 153, 102));
        btn_recuperarSenha.setText("Esqueci minha senha");
        btn_recuperarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_recuperarSenhaMouseClicked(evt);
            }
        });

        btn_adcUsuario.setForeground(new java.awt.Color(0, 153, 102));
        btn_adcUsuario.setText("Cadastrar");
        btn_adcUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adcUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(btn_recuperarSenha)
                                .addComponent(btn_login))
                            .addComponent(btn_adcUsuario, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txt_usuario)
                            .addComponent(txt_senha, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_usuario)
                            .addComponent(lbl_senha))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_login)
                .addGap(18, 18, 18)
                .addComponent(btn_recuperarSenha)
                .addGap(18, 18, 18)
                .addComponent(btn_adcUsuario)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        List<Usuarios> listaUsuarios = new ArrayList();
        boolean autorizarLogin = false;
        String usuarioNome = txt_usuario.getText();
        String senha = new String(txt_senha.getPassword()).trim();
        
        try{
            listaUsuarios = controlador.consultar();
            Usuarios usuario = new Usuarios();
            
            for(int i=0;i<listaUsuarios.size();i++){
                if(usuarioNome.equals(listaUsuarios.get(i).getUsuario()) &&
                        senha.equals(listaUsuarios.get(i).getSenha())){
                    autorizarLogin = true;
                    
                    usuario.setId(listaUsuarios.get(i).getId());
                    usuario.setUsuario(listaUsuarios.get(i).getUsuario());
                    usuario.setSenha(listaUsuarios.get(i).getSenha());
                }
            }
            
            if(autorizarLogin) {
                MainScreen telaPrincipal = new MainScreen();
                telaPrincipal.setUsuario(usuario);
                telaPrincipal.setVisible(true);
                this.dispose();
            }
            else JOptionPane.showMessageDialog(rootPane, "Usuário ou Senha incorretos");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Não foi possível conectar com o banco de Dados\n"
                    + "Tente novamente em instantes","Falha na conexão",0);
            throw new RuntimeException("Não foi possível conectar com o banco de Dados\n" + e.getMessage(),e);
        }
    }//GEN-LAST:event_btn_loginMouseClicked

    private void btn_recuperarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recuperarSenhaMouseClicked
        String nomeUsuario = JOptionPane.showInputDialog(rootPane, "Usuário", "",-1);
        List<Usuarios> listaUsuarios = new ArrayList();
        listaUsuarios = controlador.consultar();
        boolean redefinirSenha = false;
        
        for(int i = 0; i < listaUsuarios.size(); i++){
            if(nomeUsuario.equals(listaUsuarios.get(i).getUsuario())){
                Usuarios usuario = new Usuarios();
                usuario.setId(listaUsuarios.get(i).getId());
                usuario.setUsuario(nomeUsuario);
                usuario.setSenha("");
                
                AdcUsuarioScreen telaUsuario = new AdcUsuarioScreen(this, rootPaneCheckingEnabled, usuario);
                telaUsuario.setVisible(true);
                
                redefinirSenha = true;
            }
            
            if(redefinirSenha == false) JOptionPane.showMessageDialog(rootPane, "Usuário não localizado", "Erro", 0);
        }
    }//GEN-LAST:event_btn_recuperarSenhaMouseClicked

    private void btn_adcUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adcUsuarioMouseClicked
        AdcUsuarioScreen telaAdcUsuario = new AdcUsuarioScreen(this, rootPaneCheckingEnabled);
        telaAdcUsuario.setVisible(true);
    }//GEN-LAST:event_btn_adcUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java Swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_adcUsuario;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel btn_recuperarSenha;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_titulo;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
