/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjetoController;
import controller.TarefaController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import model.Projetos;
import model.Tarefas;
import util.TabTarefasModel;

/**
 *
 * @author jbali
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    //ATRIBUTOS
    ProjetoController projetoController;
    TarefaController tarefaController;
    DefaultListModel modeloProjeto;
    TabTarefasModel modeloTarefas;
    
    
    //MÉTODOS DE COMPONENTES    
    public MainScreen() {
        initComponents();//Inicializa os componentes da janela
        iniciarControllers();//Inicializa os controladores
        iniciarComponentModel();//Inicializa os modelos dos componentes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_listaVazia = new javax.swing.JPanel();
        lbl_listaVaziaIcon = new javax.swing.JLabel();
        lbl_listaVaziaTitulo = new javax.swing.JLabel();
        lbl_listaVaziaSub = new javax.swing.JLabel();
        pnl_titulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_motto = new javax.swing.JLabel();
        pnl_adcProjeto = new javax.swing.JPanel();
        lbl_adcProjeto = new javax.swing.JLabel();
        btn_adcProjeto = new javax.swing.JLabel();
        pnl_adcTarefa = new javax.swing.JPanel();
        lbl_adcTarefa = new javax.swing.JLabel();
        btn_adcTarefa = new javax.swing.JLabel();
        pnl_listaProjetos = new javax.swing.JPanel();
        spn_listaProjetos = new javax.swing.JScrollPane();
        lst_Projetos = new javax.swing.JList<>();
        pnl_listaTarefas = new javax.swing.JPanel();
        spn_listaTarefas = new javax.swing.JScrollPane();
        tab_listaTarefas = new javax.swing.JTable();

        pnl_listaVazia.setBackground(new java.awt.Color(255, 255, 255));

        lbl_listaVaziaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_listaVaziaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        lbl_listaVaziaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_listaVaziaTitulo.setForeground(new java.awt.Color(0, 153, 102));
        lbl_listaVaziaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_listaVaziaTitulo.setText("Nenhuma tarefa por aqui :D");

        lbl_listaVaziaSub.setForeground(new java.awt.Color(153, 153, 153));
        lbl_listaVaziaSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_listaVaziaSub.setText("Clique no botão \"+\" para adicionar uma nofa tarefa");

        javax.swing.GroupLayout pnl_listaVaziaLayout = new javax.swing.GroupLayout(pnl_listaVazia);
        pnl_listaVazia.setLayout(pnl_listaVaziaLayout);
        pnl_listaVaziaLayout.setHorizontalGroup(
            pnl_listaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_listaVaziaIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_listaVaziaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_listaVaziaSub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        pnl_listaVaziaLayout.setVerticalGroup(
            pnl_listaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listaVaziaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_listaVaziaIcon)
                .addGap(18, 18, 18)
                .addComponent(lbl_listaVaziaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_listaVaziaSub)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TodoApp");
        setMinimumSize(new java.awt.Dimension(650, 700));

        pnl_titulo.setBackground(new java.awt.Color(0, 153, 102));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        lbl_titulo.setText(" TodoApp");

        lbl_motto.setForeground(new java.awt.Color(255, 255, 255));
        lbl_motto.setText("Anote tudo, não esqueça nada");

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_motto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbl_titulo)
                .addGap(18, 18, 18)
                .addComponent(lbl_motto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_adcProjeto.setBackground(new java.awt.Color(255, 255, 255));

        lbl_adcProjeto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_adcProjeto.setForeground(new java.awt.Color(0, 153, 102));
        lbl_adcProjeto.setText("Projetos");

        btn_adcProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btn_adcProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adcProjetoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_adcProjetoLayout = new javax.swing.GroupLayout(pnl_adcProjeto);
        pnl_adcProjeto.setLayout(pnl_adcProjetoLayout);
        pnl_adcProjetoLayout.setHorizontalGroup(
            pnl_adcProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adcProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adcProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btn_adcProjeto)
                .addContainerGap())
        );
        pnl_adcProjetoLayout.setVerticalGroup(
            pnl_adcProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adcProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_adcProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_adcProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_adcProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_adcTarefa.setBackground(new java.awt.Color(255, 255, 255));

        lbl_adcTarefa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_adcTarefa.setForeground(new java.awt.Color(0, 153, 102));
        lbl_adcTarefa.setText("Tarefas");

        btn_adcTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btn_adcTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adcTarefaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_adcTarefaLayout = new javax.swing.GroupLayout(pnl_adcTarefa);
        pnl_adcTarefa.setLayout(pnl_adcTarefaLayout);
        pnl_adcTarefaLayout.setHorizontalGroup(
            pnl_adcTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adcTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adcTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_adcTarefa)
                .addContainerGap())
        );
        pnl_adcTarefaLayout.setVerticalGroup(
            pnl_adcTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adcTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_adcTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_adcTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_adcTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_listaProjetos.setBackground(new java.awt.Color(255, 255, 255));

        spn_listaProjetos.setBorder(null);

        lst_Projetos.setBackground(new java.awt.Color(255, 255, 255));
        lst_Projetos.setBorder(null);
        lst_Projetos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lst_Projetos.setForeground(new java.awt.Color(0, 153, 102));
        lst_Projetos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_Projetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_Projetos.setFixedCellHeight(40);
        lst_Projetos.setSelectionBackground(new java.awt.Color(0, 153, 102));
        lst_Projetos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        lst_Projetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_ProjetosMouseClicked(evt);
            }
        });
        spn_listaProjetos.setViewportView(lst_Projetos);

        javax.swing.GroupLayout pnl_listaProjetosLayout = new javax.swing.GroupLayout(pnl_listaProjetos);
        pnl_listaProjetos.setLayout(pnl_listaProjetosLayout);
        pnl_listaProjetosLayout.setHorizontalGroup(
            pnl_listaProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listaProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spn_listaProjetos)
                .addContainerGap())
        );
        pnl_listaProjetosLayout.setVerticalGroup(
            pnl_listaProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listaProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spn_listaProjetos)
                .addContainerGap())
        );

        pnl_listaTarefas.setBackground(new java.awt.Color(255, 255, 255));
        pnl_listaTarefas.setLayout(new java.awt.BorderLayout());

        spn_listaTarefas.setBackground(new java.awt.Color(255, 255, 255));
        spn_listaTarefas.setBorder(null);

        tab_listaTarefas.setBackground(new java.awt.Color(255, 255, 255));
        tab_listaTarefas.setForeground(new java.awt.Color(0, 153, 102));
        tab_listaTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Concluído"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_listaTarefas.setFillsViewportHeight(true);
        tab_listaTarefas.setGridColor(new java.awt.Color(0, 153, 102));
        tab_listaTarefas.setRowHeight(40);
        tab_listaTarefas.setSelectionBackground(new java.awt.Color(0, 153, 102));
        tab_listaTarefas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tab_listaTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tab_listaTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tab_listaTarefas.setShowGrid(false);
        tab_listaTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_listaTarefasMouseClicked(evt);
            }
        });
        spn_listaTarefas.setViewportView(tab_listaTarefas);

        pnl_listaTarefas.add(spn_listaTarefas, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnl_listaProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_adcProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_adcTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_listaTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_adcProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_adcTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_listaTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_listaProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adcProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adcProjetoMouseClicked
        // TODO add your handling code here:
        AdcProjetoScreen telaCadProj = new AdcProjetoScreen(this, rootPaneCheckingEnabled);
        telaCadProj.setVisible(true);
        
        //Cria um listener para atualização da lista de projetos
        telaCadProj.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent e){
                carregarProjetos();//Atualiza a lista
            }
        });
    }//GEN-LAST:event_btn_adcProjetoMouseClicked

    private void btn_adcTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adcTarefaMouseClicked
        //Cria a janela de adição de tarefas
        AdcTarefaScreen telaCadTarefa = new AdcTarefaScreen(this, rootPaneCheckingEnabled);
        
        //Passa o projeto selecionado à janela de adição de tarefas
        int indiceProjeto = lst_Projetos.getSelectedIndex();
        Projetos projeto = (Projetos) modeloProjeto.get(indiceProjeto);
        telaCadTarefa.setProjeto(projeto);
        
        //Abre a janela de adição de tarefas
        telaCadTarefa.setVisible(true);
        
        /**
         * Cria um listener para atualizar a tabela quando a janela de adição de 
         * tarefas for fechada
         */
        telaCadTarefa.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent e){
                carregarTarefas(projeto.getId());//Atualiza a lista    
            }
        });
    }//GEN-LAST:event_btn_adcTarefaMouseClicked

    private void lst_ProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_ProjetosMouseClicked
        int proj_indice = lst_Projetos.getSelectedIndex();//Recebe o índice do item selecionado
        
        //Cria um objeto Projeto a partir dos objetos da lista de modelo de projetos
        Projetos projeto = (Projetos) modeloProjeto.get(proj_indice);
        carregarTarefas(projeto.getId());//Carrega as tarefas do projeto selecionado
    }//GEN-LAST:event_lst_ProjetosMouseClicked

    private void tab_listaTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_listaTarefasMouseClicked
        //Variáveis que receberão o ponto em que a tabela foi clicada
        int indiceLinha = tab_listaTarefas.rowAtPoint(evt.getPoint());
        int indiceColuna = tab_listaTarefas.columnAtPoint(evt.getPoint());
        
        //Cria um objeto Tarefa que recebe a tarefa clicada
        Tarefas tarefa = modeloTarefas.getListaTarefas().get(indiceLinha);
        
        //Define a ação a ser tomada com base na coluna em que o clique ocorreu
        switch(indiceColuna){
            case 3://(checkbox)
                tarefaController.atualizar(tarefa);//Atualiza a tarefa clicada
                break;
            case 5://(excluir)
                tarefaController.excluir(tarefa.getId());//Exclui do BD a tarefa clicada
                modeloTarefas.getListaTarefas().remove(tarefa);//Exclui a tarefa da lista
                carregarTarefas(tarefa.getProj_id());//Recarrega a tabela de tarefas
                break;
        }
    }//GEN-LAST:event_tab_listaTarefasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java Swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_adcProjeto;
    private javax.swing.JLabel btn_adcTarefa;
    private javax.swing.JLabel lbl_adcProjeto;
    private javax.swing.JLabel lbl_adcTarefa;
    private javax.swing.JLabel lbl_listaVaziaIcon;
    private javax.swing.JLabel lbl_listaVaziaSub;
    private javax.swing.JLabel lbl_listaVaziaTitulo;
    private javax.swing.JLabel lbl_motto;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JList<String> lst_Projetos;
    private javax.swing.JPanel pnl_adcProjeto;
    private javax.swing.JPanel pnl_adcTarefa;
    private javax.swing.JPanel pnl_listaProjetos;
    private javax.swing.JPanel pnl_listaTarefas;
    private javax.swing.JPanel pnl_listaVazia;
    private javax.swing.JPanel pnl_titulo;
    private javax.swing.JScrollPane spn_listaProjetos;
    private javax.swing.JScrollPane spn_listaTarefas;
    private javax.swing.JTable tab_listaTarefas;
    // End of variables declaration//GEN-END:variables

    
    //MÉTODOS
    public void decorarTabela(){
        //Personaliza as cores do cabeçalho da tabela
        tab_listaTarefas.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));//Define a fonte
        tab_listaTarefas.getTableHeader().setBackground(new Color(0,153,102));//Define a cor de fundo
        tab_listaTarefas.getTableHeader().setForeground(new Color(255,255,255));//Define a cor da fonte
        tab_listaTarefas.setAutoCreateRowSorter(true);
        
        //Centraliza coluna Prazo
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(JLabel.CENTER);
        tab_listaTarefas.getColumnModel().getColumn(2).setCellRenderer(centralizado);
    }
    
    public void iniciarControllers(){
        projetoController = new ProjetoController();
        tarefaController = new TarefaController();
    }
    
    public void iniciarComponentModel(){
        //Iniciar lista de projetos
        modeloProjeto = new DefaultListModel();
        carregarProjetos();
        
        //Iniciar tabela de tarefas
        modeloTarefas = new TabTarefasModel();
        tab_listaTarefas.setModel(modeloTarefas);
        decorarTabela();
        
        //Seleciona o primeiro projeto da lista e carrega suas tarefas
        if(!modeloProjeto.isEmpty()){//Se a lista de projetos não estiver vazia
            lst_Projetos.setSelectedIndex(0);//Seleciona o primeiro projeto
            
            //Cria um objeto Projeto com o primeiro item da lista de projetos
            Projetos projeto = (Projetos) modeloProjeto.get(0);
            
            //Carrega as tarefas do projeto
            carregarTarefas(projeto.getId());
        }
    }

    private void carregarProjetos() {
        //Cria uma estrutura de dados de lista que recebe todos os dados de projetos do BD
        List<Projetos> listaProjetos = projetoController.consultar();
        
        modeloProjeto.clear();//Limpa o modelo
        
        for(int i=0; i<listaProjetos.size();i++){
            //Cria um objeto Projeto que recebe um elemento da lista
            Projetos projeto = listaProjetos.get(i);
            
            //Insere o projeto no modelo de lista
            modeloProjeto.addElement(projeto);
        }
        
        //Define o objeto modelo como lista do componente
        lst_Projetos.setModel(modeloProjeto);
    }
    
    private void carregarTarefas(int proj_id){
        List<Tarefas> tarefas = tarefaController.consultar(proj_id);
        modeloTarefas.setListaTarefas(tarefas);
        
        //Se a lista de tarefas não estiver vazia, envia um temTarefas (true)
        mostrarTarefas(!tarefas.isEmpty());
    }
    
    private void mostrarTarefas(boolean temTarefas){
        if(temTarefas){
            if(pnl_listaVazia.isVisible()){
                pnl_listaVazia.setVisible(false);
                pnl_listaTarefas.remove(pnl_listaVazia);
            }
            
            pnl_listaTarefas.add(spn_listaTarefas);
            spn_listaTarefas.setVisible(true);
            spn_listaTarefas.setSize(pnl_listaTarefas.getWidth(), pnl_listaTarefas.getHeight());
        }else{
            if(spn_listaTarefas.isVisible()){
                spn_listaTarefas.setVisible(false);
                pnl_listaTarefas.remove(spn_listaTarefas);
            }
            
            pnl_listaTarefas.add(pnl_listaVazia);
            pnl_listaVazia.setVisible(true);
            pnl_listaVazia.setSize(pnl_listaTarefas.getWidth(), pnl_listaTarefas.getHeight());
        }
    }
}
